### ISSUE TITLE
Single Pass Instancedを有効にすると右目にエフェクトの描画が行われない (Effects on the right eye screen was not rendered when rendering in Single Pass Instanced)

### ISSUE THREAD

**Issue by amamagi** [effekseer/EffekseerForUnity#54]
## 概要
XR設定を有効にして Stereo Rendering Mode を Single Pass Instanced にすると、右目の画面にエフェクトがレンダリングされません。
![image](https://user-images.githubusercontent.com/36906576/113142645-174a5900-9266-11eb-8dbf-ac4edfd0bce5.png)

## 再現方法
1. 新規Unityプロジェクトに SteamVR と EffekseerForUnity をインポートする
2. [Edit] > [ProjectSettngs] より ProjectSettings ダイアログを開き、左ペインから[XR Plug-in Management]>[OpenVR]を選択し、[Stereo Rendering Mode] のドロップダウンメニューから [Single Pass Instanced] を選択する
3. `EfkBasic` シーンを再生する

## 再現環境
- OS: Windows 10 Pro 20H2 64bit
- Unity: 2020.3.1f1(with XR Plugin), 2019.4.23f1(with built-in XR)
- XR Platform: SteamVR(OpenVR)
- EffekseerFroUnity: 1.60beta2

**Comment by amamagi** [comment]
よろしくお願いします。
RendererをUnityに変更して確認しましたが、状況は改善しませんでした。

**Comment by durswd** [comment]
了解しました。UnityRendererのほうは、ネイティブでなくUnityのCommandBufferから描画命令を呼んでいるのですが、ただUnityの描画命令を使用するだけでは対応できないようです。

時間がかかるかもしれませんが調査はしてみます。
